
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/escuela_conductores_db
    username: postgres
    password: prueba
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
